# Workflow for testing the code
name: Run tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Setup node
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '17.5.0'

      # Install node dependencies
      - name: Install node dependencies
        run: npm ci